"""Independent historical stock-selection backtesting package.

Production screening and simulated trading never import this package.
"""

from .historical_data import (
    DEFAULT_HISTORICAL_SOURCE_PRIORITY,
    HistoricalDataError,
    HistoricalDataResult,
    HistoricalDataSummary,
    HistoricalFetchConfig,
    HistoricalSeries,
    HistoricalSeriesSummary,
    SUPPORTED_ADJUSTMENTS,
    SUPPORTED_HISTORICAL_SOURCES,
    fetch_historical_data,
    fetch_historical_series,
    normalize_a_share_symbol,
)
from .selection import (
    HistoricalBar,
    HistoricalFlowProvider,
    NiuOneHistoricalContextProvider,
    PortfolioEntryDecision,
    PositionExitSignal,
    PositionExitStrategy,
    RegisteredScorerSelector,
    ReplaySelectionStrategy,
    SectorTideHistoricalContextProvider,
    SelectionBacktestConfig,
    SelectionBacktestError,
    SelectionBacktestResult,
    SelectionContext,
    SelectionCostModel,
    SelectionFunction,
    SelectionPreparation,
    SelectionReplayFrame,
    SelectionReplayProgress,
    SelectionReplayTape,
    SelectionSignal,
    SelectionSignalFilter,
    SelectionStrategy,
    a_share_price_limits,
    build_selection_replay_tape,
    run_selection_backtest,
)
from .replay_cache import ReplayCacheKey, ReplayTapeCache, build_replay_cache_key
from .niuone_exits import NiuOneDailyExitStrategy, NiuOneStrategyBacktestPolicy
from .prompt_strategy import (
    PROMPT_BACKTEST_PROTOCOL_VERSION,
    PromptStrategyBacktestPolicy,
    PromptStrategyHistoricalSelector,
    prompt_backtest_version_snapshot,
    validate_prompt_backtest_version,
)
from .service import (
    HistoricalSelectionBacktestRun,
    IndustryAnnotationQuality,
    IndustryMapLoader,
    ThemeMapLoader,
    load_current_industry_map,
    load_current_theme_map,
    run_historical_selection_backtest,
)


__all__ = [
    "DEFAULT_HISTORICAL_SOURCE_PRIORITY",
    "HistoricalBar",
    "HistoricalDataError",
    "HistoricalDataResult",
    "HistoricalDataSummary",
    "HistoricalFetchConfig",
    "HistoricalFlowProvider",
    "HistoricalSelectionBacktestRun",
    "HistoricalSeries",
    "HistoricalSeriesSummary",
    "IndustryAnnotationQuality",
    "IndustryMapLoader",
    "ThemeMapLoader",
    "NiuOneHistoricalContextProvider",
    "NiuOneDailyExitStrategy",
    "NiuOneStrategyBacktestPolicy",
    "PROMPT_BACKTEST_PROTOCOL_VERSION",
    "PortfolioEntryDecision",
    "PositionExitSignal",
    "PositionExitStrategy",
    "PromptStrategyBacktestPolicy",
    "PromptStrategyHistoricalSelector",
    "RegisteredScorerSelector",
    "ReplaySelectionStrategy",
    "ReplayCacheKey",
    "ReplayTapeCache",
    "SectorTideHistoricalContextProvider",
    "SUPPORTED_ADJUSTMENTS",
    "SUPPORTED_HISTORICAL_SOURCES",
    "SelectionBacktestConfig",
    "SelectionBacktestError",
    "SelectionBacktestResult",
    "SelectionContext",
    "SelectionCostModel",
    "SelectionFunction",
    "SelectionPreparation",
    "SelectionReplayFrame",
    "SelectionReplayProgress",
    "SelectionReplayTape",
    "SelectionSignal",
    "SelectionSignalFilter",
    "SelectionStrategy",
    "a_share_price_limits",
    "build_selection_replay_tape",
    "build_replay_cache_key",
    "fetch_historical_data",
    "fetch_historical_series",
    "load_current_industry_map",
    "load_current_theme_map",
    "normalize_a_share_symbol",
    "prompt_backtest_version_snapshot",
    "run_historical_selection_backtest",
    "run_selection_backtest",
    "validate_prompt_backtest_version",
]
