[CmdletBinding()]
param(
    [switch]$NoBrowser,
    [switch]$SkipInstall,
    [switch]$Help
)

$ErrorActionPreference = "Stop"

function Show-Usage {
    @"
NiuOne one-click local runner for Windows

Usage:
  .\run.ps1 [options]

Options:
  -NoBrowser     Do not open the browser automatically
  -SkipInstall   Skip dependency installation
  -Help          Show this help

Environment:
  NIUONE_LOCAL_DATA_DIR  Private runtime directory, default: .local-data
  DASHBOARD_HOST         Dashboard host, default: 127.0.0.1
  DASHBOARD_PORT         Dashboard port, default: 8787
  DASHBOARD_AUTH_ENABLED Local auth switch, default on first run: 0
"@
}

if ($Help) {
    Show-Usage
    exit 0
}

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

function Get-EnvOrDefault {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][string]$Default
    )
    $Value = [Environment]::GetEnvironmentVariable($Name, "Process")
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $Default
    }
    return $Value
}

function ConvertTo-EnvValue {
    param([AllowNull()][string]$Value)
    if ($null -eq $Value) {
        return ""
    }
    return $Value
}

function New-DefaultEnvFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$LocalDataDir,
        [Parameter(Mandatory = $true)][string]$VenvDir
    )

    New-Item -ItemType Directory -Force -Path $LocalDataDir | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $LocalDataDir "runtime\cron\output") | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $LocalDataDir "runtime\logs") | Out-Null
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null

    $DashboardHome = Join-Path $LocalDataDir "runtime"
    $Lines = @(
        "# Generated by .\run.ps1. Keep this file private.",
        "# Edit it directly or use /admin after the dashboard starts.",
        "DASHBOARD_HOME=$(ConvertTo-EnvValue $DashboardHome)",
        "DASHBOARD_HOST=$(Get-EnvOrDefault "DASHBOARD_HOST" "127.0.0.1")",
        "DASHBOARD_PORT=$(Get-EnvOrDefault "DASHBOARD_PORT" "8787")",
        "PYTHON_BIN=$(ConvertTo-EnvValue (Join-Path $VenvDir "Scripts\python.exe"))",
        "",
        "DASHBOARD_CONFIG=$(ConvertTo-EnvValue (Join-Path $DashboardHome "config.yaml"))",
        "DASHBOARD_PUSH_HISTORY_DB=$(ConvertTo-EnvValue (Join-Path $DashboardHome "push_history.db"))",
        "DASHBOARD_PORTFOLIO_STATE=$(ConvertTo-EnvValue (Join-Path $DashboardHome "cron\output\niuniu_practice_portfolio.json"))",
        "DASHBOARD_TRADER_SCRIPT=$(ConvertTo-EnvValue (Join-Path $Root "app\niuniu_practice_trader.py"))",
        "",
        "# Local-first default: no login required on 127.0.0.1.",
        "# If you expose the dashboard beyond your own machine, set this to 1 and configure access.",
        "DASHBOARD_AUTH_ENABLED=$(Get-EnvOrDefault "DASHBOARD_AUTH_ENABLED" "0")",
        "DASHBOARD_ADMIN_PASSWORD=$(Get-EnvOrDefault "DASHBOARD_ADMIN_PASSWORD" "")"
    )
    $Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllLines($Path, $Lines, $Utf8NoBom)
}

function Import-DashboardEnv {
    param([Parameter(Mandatory = $true)][string]$Path)
    foreach ($RawLine in Get-Content -Path $Path -Encoding UTF8) {
        $Line = $RawLine.Trim()
        if ($Line.Length -eq 0 -or $Line.StartsWith("#")) {
            continue
        }
        $Index = $Line.IndexOf("=")
        if ($Index -lt 1) {
            continue
        }
        $Name = $Line.Substring(0, $Index).Trim()
        $Value = $Line.Substring($Index + 1).Trim()
        if (($Value.StartsWith('"') -and $Value.EndsWith('"')) -or ($Value.StartsWith("'") -and $Value.EndsWith("'"))) {
            $Value = $Value.Substring(1, $Value.Length - 2)
        }
        [Environment]::SetEnvironmentVariable($Name, $Value, "Process")
    }
}

function Test-PythonCommand {
    param(
        [Parameter(Mandatory = $true)][string]$Command,
        [string[]]$PrefixArgs = @()
    )
    try {
        & $Command @PrefixArgs --version *> $null
        return $true
    } catch {
        return $false
    }
}

function Set-PythonLauncher {
    if (Test-PythonCommand "python") {
        $script:PythonLauncherCommand = "python"
        $script:PythonLauncherArgs = @()
        return
    }
    if (Test-PythonCommand "py" @("-3")) {
        $script:PythonLauncherCommand = "py"
        $script:PythonLauncherArgs = @("-3")
        return
    }
    if (Test-PythonCommand "python3") {
        $script:PythonLauncherCommand = "python3"
        $script:PythonLauncherArgs = @()
        return
    }
    throw "Python 3 is required but was not found in PATH."
}

function Invoke-PythonLauncher {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments)
    & $script:PythonLauncherCommand @script:PythonLauncherArgs @Arguments
}

$LocalDataDir = Get-EnvOrDefault "NIUONE_LOCAL_DATA_DIR" (Join-Path $Root ".local-data")
$VenvDir = Get-EnvOrDefault "NIUONE_VENV_DIR" (Join-Path $LocalDataDir ".venv")
$EnvFile = Get-EnvOrDefault "DASHBOARD_ENV_FILE" (Join-Path $LocalDataDir "dashboard.env")

if (-not (Test-Path $EnvFile)) {
    Write-Host "== First run: creating private runtime files =="
    New-DefaultEnvFile -Path $EnvFile -LocalDataDir $LocalDataDir -VenvDir $VenvDir
}

Import-DashboardEnv $EnvFile

$DashboardHome = Get-EnvOrDefault "DASHBOARD_HOME" (Join-Path $LocalDataDir "runtime")
$DashboardHost = Get-EnvOrDefault "DASHBOARD_HOST" "127.0.0.1"
$DashboardPort = Get-EnvOrDefault "DASHBOARD_PORT" "8787"
$DefaultPythonBin = Join-Path $VenvDir "Scripts\python.exe"
$ConfiguredPythonBin = Get-EnvOrDefault "PYTHON_BIN" $DefaultPythonBin
$PythonBin = if (Test-Path $ConfiguredPythonBin) { $ConfiguredPythonBin } else { $DefaultPythonBin }

New-Item -ItemType Directory -Force -Path (Join-Path $DashboardHome "cron\output") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $DashboardHome "logs") | Out-Null
New-Item -ItemType Directory -Force -Path $LocalDataDir | Out-Null

$VenvCreated = $false
if (-not (Test-Path $PythonBin)) {
    Write-Host "== Creating Python virtual environment =="
    Set-PythonLauncher
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $VenvDir) | Out-Null
    Invoke-PythonLauncher "-m" "venv" $VenvDir
    $PythonBin = $DefaultPythonBin
    $VenvCreated = $true
}

if (-not $SkipInstall) {
    $Requirements = Join-Path $Root "requirements.txt"
    $ReqHash = (& $PythonBin -c "from hashlib import sha256; from pathlib import Path; import sys; print(sha256(Path(sys.argv[1]).read_bytes()).hexdigest())" $Requirements).Trim()
    $ReqMarker = Join-Path $LocalDataDir ".requirements.sha256"
    $InstalledHash = if (Test-Path $ReqMarker) { (Get-Content -Path $ReqMarker -Raw).Trim() } else { "" }
    if ($VenvCreated -or $ReqHash -ne $InstalledHash) {
        Write-Host "== Installing Python dependencies =="
        & $PythonBin -m pip install --upgrade pip
        & $PythonBin -m pip install -r $Requirements
        Set-Content -Path $ReqMarker -Value $ReqHash -Encoding ASCII
    } else {
        Write-Host "== Python dependencies are up to date =="
    }
} else {
    Write-Host "== Skipping dependency installation =="
}

$Url = "http://${DashboardHost}:${DashboardPort}/"
Write-Host "== Starting NiuOne Dashboard =="
Write-Host "  URL:        $Url"
Write-Host "  data:       $DashboardHome"
Write-Host "  env:        $EnvFile"
Write-Host "  stop:       Ctrl+C"

if (-not $NoBrowser) {
    Start-Job -ArgumentList $DashboardHost, $DashboardPort, $Url -ScriptBlock {
        param($HostName, $Port, $Url)
        for ($i = 0; $i -lt 80; $i++) {
            try {
                $Client = [System.Net.Sockets.TcpClient]::new()
                $Async = $Client.BeginConnect($HostName, [int]$Port, $null, $null)
                if ($Async.AsyncWaitHandle.WaitOne(250) -and $Client.Connected) {
                    $Client.Close()
                    Start-Process $Url
                    return
                }
                $Client.Close()
            } catch {
            }
            Start-Sleep -Milliseconds 250
        }
    } | Out-Null
}

$env:DASHBOARD_ENV_FILE = $EnvFile
$env:DASHBOARD_HOME = $DashboardHome
$env:DASHBOARD_HOST = $DashboardHost
$env:DASHBOARD_PORT = $DashboardPort
$env:PYTHON_BIN = $PythonBin
$env:PYTHONDONTWRITEBYTECODE = Get-EnvOrDefault "PYTHONDONTWRITEBYTECODE" "1"
$env:DASHBOARD_CONFIG = Get-EnvOrDefault "DASHBOARD_CONFIG" (Join-Path $DashboardHome "config.yaml")
$env:DASHBOARD_PUSH_HISTORY_DB = Get-EnvOrDefault "DASHBOARD_PUSH_HISTORY_DB" (Join-Path $DashboardHome "push_history.db")
$env:DASHBOARD_PORTFOLIO_STATE = Get-EnvOrDefault "DASHBOARD_PORTFOLIO_STATE" (Join-Path $DashboardHome "cron\output\niuniu_practice_portfolio.json")
$env:DASHBOARD_TRADER_SCRIPT = Get-EnvOrDefault "DASHBOARD_TRADER_SCRIPT" (Join-Path $Root "app\niuniu_practice_trader.py")

& $PythonBin (Join-Path $Root "app\niuone_dashboard.py") --host $DashboardHost --port ([int]$DashboardPort)
exit $LASTEXITCODE
